# 1602 LCD (PCF8574 I2C) + ADXL345 가속도계 테스트 빌드 설정

CONFIG_I2C=y
CONFIG_PINCTRL=y
CONFIG_GPIO=y

CONFIG_SENSOR=y
CONFIG_ADXL345=y
CONFIG_ADXL345_TRIGGER_NONE=y

CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_LOG_MODE_IMMEDIATE=y

CONFIG_CBPRINTF_FP_SUPPORT=y
